### ISSUE TITLE
[BUG] No auto-refreshes

### ISSUE THREAD

**Issue by chrissxYT** [Amplissimus/Amplissimus#14]
**Describe the bug**
If the app isn’t restarted it doesn‘t refresh automatically, which creates a lot of problems.

**To Reproduce**
1. Open app
2. Leave (don‘t close it)
3. Come back hours later

**Expected behavior**
Reload automatically if in foreground.

**Versions (please complete the following information):**
 - OS/Browser version: iOS 13.5 (any)
 - Version: 1.2.1 (any)

**Comment by Luddifee** [comment]
Added this feature in commit 23086b1.
