### ISSUE TITLE
[BUG] App not closing, when 'Close App on Back Press is marked as true'

### ISSUE THREAD

**Issue by Luddifee** [Amplissimus/Amplissimus#16]
**Describe the bug**
If 'Close App on Back Press' is marked as true in the dev options, the App would not close.

**To Reproduce**
1. Go to dev options
2. Click on 'Close App on Back Press' to mark it as true
4. Go back to home screen
5. Click your back Button on your phone
6. App not closing

**Expected behavior**
App should close

**Screenshots/Stacktraces/Logs**
If applicable, add screenshots, stacktraces or logs to help explain your problem.

**Versions (please complete the following information):**
 - latest

**Additional context**

**Comment by chrissxYT** [comment]
just reproduced on Android 7.0 with almost master

**Comment by chrissxYT** [comment]
05214680d01be634ab9cf190520014f5a92b6254 might has fixed this (havent checked)

**Comment by chrissxYT** [comment]
it has
